// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// get_dist_cat.cpp
doubles get_dist_cat(strings x, strings_matrix<> y);
extern "C" SEXP _RSBID_get_dist_cat(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_dist_cat(cpp11::as_cpp<cpp11::decay_t<strings>>(x), cpp11::as_cpp<cpp11::decay_t<strings_matrix<>>>(y)));
  END_CPP11
}
// get_dist_cont.cpp
doubles get_dist_cont(doubles x, doubles_matrix<> y);
extern "C" SEXP _RSBID_get_dist_cont(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_dist_cont(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(y)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_RSBID_get_dist_cat",  (DL_FUNC) &_RSBID_get_dist_cat,  2},
    {"_RSBID_get_dist_cont", (DL_FUNC) &_RSBID_get_dist_cont, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_RSBID(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
