# Generated by using Rcpp::compileAttributes() -> do not edit by hand Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_dist_cat <- function(x, y) {
    .Call("_RSBID_get_dist_cat", PACKAGE = "RSBID", x, y)
}

get_dist_cont <- function(x, y) {
    .Call("_RSBID_get_dist_cont", PACKAGE = "RSBID", x, y)
}

